/** Generated by scripts/write-deploy-env.cjs — do not edit. */
export const environment = {
  production: true,
  apiBaseUrl: "https://mishkatulilm-api.fly.dev",
  supabaseUrl: "https://x.supabase.co",
  supabaseAnonKey: "test-key",
};
